---
# Python 3 with Redis
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    volumes:
      - ..:/app
    command: sleep infinity
    environment:
      FLASK_ENV: development
      DATABASE_URI: redis://redis:6379/0
    networks:
      - dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - dev

volumes:
  redis:

networks:
  dev:
