name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    # Required services    
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
        env:
          DATABASE_URI: "redis://redis:6379/0"

      - name: Upload code coverage
        uses: codecov/codecov-action@v2  
        with:
          files: ./coverage.xml
          flags: unittests