name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    # # Required services    
    # services:
    #   redis:
    #     image: redis:6-alpine
    #     ports:
    #       - 6379:6379
    #     options: >-
    #       --health-cmd redis-cli ping
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Redis v6
      #   uses: shogo82148/actions-setup-redis@v1
      #   with:
      #     redis-version: '6.x'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - name: Check if Redis is ready
        run: redis-cli ping

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE_URI: "redis://localhost:6379/0"

      - name: Upload code coverage
        uses: codecov/codecov-action@v2  
  